### ISSUE TITLE
Wrong license text

### ISSUE THREAD

**Issue by blinxen** [postsolar/tree-sitter-purescript#5]
Thanks for a adding a license file!! It seems that the added license file contains the `Unlicense` license text. Since your repository is only a fork, I don't think you can just change the license under which the code is published. You either have to change the license text to match the `ISC` license or talk to upstream and see if he wants to re-license the project too. Did you change it willingly? If not, then you can just copy https://github.com/Maskhjarna/tree-sitter-purescript/blob/main/LICENSE.

**Comment by postsolar** [comment]
Sorry, I didn't put much thought into that. Actually upstream is itself a fork of Haskell grammar, which is MIT. Am I only allowed to license it as MIT in this case?

**Comment by blinxen** [comment]
Hm, I missed that. That would also be an issue. I will create a PR upstream and fix this.

**Comment by postsolar** [comment]
If you can arrange the text so that it separates the licensing of Haskell code and our own code it would be great. From what I understand, MIT allows one to relicense a project as long as the MIT parts are kept MIT. In case of our own code, I don't want potential distributors to be obliged to mention its origin.

**Comment by blinxen** [comment]
I just submitted https://github.com/Maskhjarna/tree-sitter-purescript/pull/30.

> In case of our own code, I don't want potential distributors to be obliged to mention its origin.

Well that is not really possible :/. If you choose to re-license it then the code will be licensed under `MIT AND ISC`. That's how it is in most distros.

**Comment by postsolar** [comment]
> under `MIT AND ISC`

If the license says something like, "Parts of this code ... Haskell/MIT ... other parts of this code ..." and then someone picks up parts which _are not_ from Haskell, are they still obliged to include the MIT license?

**Comment by postsolar** [comment]
That's what I see being said on the web on this topic. If yes then awesome, if no then I'd just opt for the most simple resolution 🙂.

**Comment by blinxen** [comment]
> If the license says something like, "Parts of this code ... Haskell/MIT ... other parts of this code ... some other license" and then someone picks up parts which are not from Haskell, are they still obliged to include the MIT license?

No but then you would have to explicitly describe what is from the original haskel code and what is 100% from you. Which is not always possible / easy. That is why I think keeping `MIT` would be best.

**Comment by blinxen** [comment]
I will close this issue and move further discussion to https://github.com/Maskhjarna/tree-sitter-purescript/pull/30.
